// <auto-generated />
using System;
using Kirjad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kirjad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112075304_rewriteDatabase")]
    partial class rewriteDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiriKiri", b =>
                {
                    b.Property<int>("SeotudKirjadId")
                        .HasColumnType("int");

                    b.Property<int>("TagasiViitedId")
                        .HasColumnType("int");

                    b.HasKey("SeotudKirjadId", "TagasiViitedId");

                    b.HasIndex("TagasiViitedId");

                    b.ToTable("KiriKiri");
                });

            modelBuilder.Entity("Kirjad.Models.Kiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("LoodudKuupaev")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pealkiri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sisu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnikaalsekKood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kirjad");

                    b.HasDiscriminator().HasValue("Kiri");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kirjad.Models.Veebiuudis", b =>
                {
                    b.HasBaseType("Kirjad.Models.Kiri");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Veebiuudis");
                });

            modelBuilder.Entity("KiriKiri", b =>
                {
                    b.HasOne("Kirjad.Models.Kiri", null)
                        .WithMany()
                        .HasForeignKey("SeotudKirjadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kirjad.Models.Kiri", null)
                        .WithMany()
                        .HasForeignKey("TagasiViitedId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
